import { App, Aspects } from 'aws-cdk-lib';
import { Annotations, Match } from 'aws-cdk-lib/assertions';
import { AwsSolutionsChecks, NagSuppressions } from 'cdk-nag';
import { PrivateRDSWithLambda } from '../src/stacks/private-rds-with-lambda';

test('Security Checks', () => {
  const app = new App();
  const stack = new PrivateRDSWithLambda(app, 'test');

  Aspects.of(app).add(new AwsSolutionsChecks());

  // Add suppressions for known/accepted risks in a demo environment
  NagSuppressions.addStackSuppressions(stack, [
    { id: 'AwsSolutions-IAM5', reason: 'Wildcard permissions are required for certain Lambda actions or are generated by CDK constructs.' },
    { id: 'AwsSolutions-IAM4', reason: 'Managed policies are used for simplicity in this demo.' },
    { id: 'AwsSolutions-L1', reason: 'Using specific runtime versions.' },
    { id: 'AwsSolutions-VPC7', reason: 'Flow logs not enabled for cost/simplicity in this demo.' },
    { id: 'AwsSolutions-SMG4', reason: 'Secret rotation not enabled for demo.' },
    { id: 'AwsSolutions-RDS3', reason: 'Multi-AZ not enabled for demo cost savings.' },
    { id: 'AwsSolutions-RDS10', reason: 'Deletion protection disabled for easier cleanup.' },
    { id: 'AwsSolutions-RDS11', reason: 'Default port used for simplicity.' },
  ]);

  const annotations = Annotations.fromStack(stack);

  // Expect no errors, but allow warnings
  annotations.hasNoError('*', Match.anyValue());
});
